### ISSUE TITLE
Input API

### ISSUE THREAD

**Issue by jgcodes2020** [mupen64/mupen64plus-core-rr#7]
This is needed for the Lua joypad API.
| Function | Spec |
|---|---|
| `BUTTONS Input_Read(int index)` | Read the current input for a controller. Do not clear overrides. |
| `void Input_Override(int index, BUTTONS a)` | Override input for this frame for a controller. |

**Comment by tosroka** [comment]
related pull request https://github.com/Mupen64-Rewrite/mupen64plus-core-rr/pull/8
